import type { Metadata } from "next";
import Link from "next/link";
import { InnerHeader } from "@/components/shell/InnerHeader";
import { SiteFooter } from "@/components/shell/SiteFooter";

export const metadata: Metadata = { title: "Hire or contract Sean / NextEleven", description: "Hire Sean McDonnell or contract NextEleven for IT, software, web presence, and applied-AI work." };

const proof = [
  { value: "12", label: "applications published on Apple’s App Store through NextEleven", boundary: "Publication record only." },
  { value: "2", label: "substantial private-client software systems completed", boundary: "Client identities and outcomes withheld." },
  { value: "376", label: "tests in the documented NextEleven Harness binary suite", boundary: "A tested public proof of concept, not an adoption claim." },
  { value: "11", label: "jobs passed in the documented cross-platform CI matrix", boundary: "Including Windows build, release, lint, and tests." },
] as const;
const roles = ["Technical support", "Implementation", "Backend engineering", "Applied AI", "Integration", "Developer tooling"] as const;

export default function WorkPage() { return <><InnerHeader current="work"/><main className="work-main">
  <section className="work-hero"><div className="path-label"><span>01</span> Hire Sean · Contract Sean · Engage NextEleven</div><p className="work-status">Mansfield, Texas · Remote United States · U.S. citizen · No sponsorship required</p><h1>Bring in the right level of help.</h1><p className="work-lede">I’m Sean McDonnell, founder of NextEleven. I’m available for employment, contract work, and consulting across IT, software, and applied AI—from a focused technical problem to a complete system.</p><div className="work-actions"><a className="primary-action" href="mailto:nextelevenstudios@gmail.com?subject=Engineering%20role">Contact for roles <span>↗</span></a><a href="/downloads/Sean-McDonnell-Technical-Support-Implementation-Engineer-Resume.pdf">Download résumé <span>↓</span></a></div></section>
  <section className="work-section"><div><p className="section-label">Hire Sean</p><h2>An engineer for the system and the people using it.</h2></div><ul className="role-list">{roles.map((role,index)=><li key={role}><span>{String(index+1).padStart(2,"0")}</span>{role}</li>)}</ul></section>
  <section className="work-section"><div><p className="section-label">Selected proof</p><h2>Specific evidence. Explicit limits.</h2></div><div className="proof-grid">{proof.map(item=><article key={item.value+item.label}><strong>{item.value}</strong><p>{item.label}</p><small>{item.boundary}</small></article>)}</div></section>
  <section className="work-section"><div><p className="section-label">Stack</p><h2>Current working range.</h2></div><div className="stack-lines"><p><span>Languages</span>Python · Rust · TypeScript / JavaScript · Kotlin · Swift · SQL · Bash</p><p><span>Backend + data</span>FastAPI · REST APIs · PostgreSQL / pgvector · SQLite · Redis · Docker</p><p><span>AI + retrieval</span>LLM APIs · tool calling · MCP · embeddings · RAG · hybrid retrieval · reranking · citations · evaluation</p><p><span>Interfaces + delivery</span>React · Next.js · SwiftUI · Jetpack Compose · GitHub Actions · automated testing · CI</p></div></section>
  <section className="work-section"><div><p className="section-label">How I work</p><h2>Investigate. Implement. Hand off.</h2></div><ol className="method-grid"><li><span>01</span><h3>Investigation</h3><p>Reproduce the failure. Read the logs. Separate the visible symptom from the system that caused it.</p></li><li><span>02</span><h3>Implementation</h3><p>Define the boundary. Build the narrowest complete repair. Test normal operation and the failure paths that matter.</p></li><li><span>03</span><h3>Handoff</h3><p>Document the limits, checks, and operating path so the work can survive without the person who wrote it.</p></li></ol></section>
  <section className="contact-strip"><p className="section-label">Role conversation</p><h2>Contact me directly.</h2><div><a className="primary-action" href="mailto:nextelevenstudios@gmail.com?subject=Engineering%20role">Contact for roles <span>↗</span></a><a href="https://www.linkedin.com/in/mothership-ai">LinkedIn <span>↗</span></a></div></section>
  <section className="consulting-section"><div className="path-label secondary"><span>02</span> Contract Sean or NextEleven</div><div className="consulting-grid"><div><h2>Consulting that can stay focused or grow into the build.</h2></div><div><p>Contract Sean directly for IT, software, AI, architecture, troubleshooting, implementation, technical direction, or hands-on delivery. Engage NextEleven when the work needs a complete software, web presence, or AI implementation.</p><p>Start with one real problem. Define the outcome and the boundary in writing. The engagement can be a short assessment, a focused repair, a defined implementation, or a longer technical partnership.</p><Link className="secondary-action" href="mailto:nextelevenstudios@gmail.com?subject=Contract%20or%20consulting%20work">Discuss contract work <span>↗</span></Link></div></div></section>
</main><SiteFooter/></>; }
