import type { Metadata } from "next";
import Link from "next/link";
import { InnerHeader } from "@/components/shell/InnerHeader";
import { SiteFooter } from "@/components/shell/SiteFooter";

export const metadata: Metadata = { title: "Work with Sean McDonnell", description: "Hiring profile for Sean McDonnell: implementation, support, backend, integration, and applied-AI engineering." };

const proof = [
  { value: "12", label: "applications published on Apple’s App Store through NextEleven", boundary: "Publication record only." },
  { value: "2", label: "substantial private-client software systems completed", boundary: "Client identities and outcomes withheld." },
  { value: "376", label: "tests in the documented NextEleven Harness binary suite", boundary: "A tested public proof of concept, not an adoption claim." },
  { value: "11", label: "jobs passed in the documented cross-platform CI matrix", boundary: "Including Windows build, release, lint, and tests." },
] as const;
const roles = ["Technical support", "Implementation", "Backend engineering", "Applied AI", "Integration", "Developer tooling"] as const;

export default function WorkPage() { return <><InnerHeader current="work"/><main className="work-main">
  <section className="work-hero"><div className="path-label"><span>01</span> Hiring · Primary path</div><p className="work-status">Mansfield, Texas · Remote United States · U.S. citizen · No sponsorship required</p><h1>Bring me the problem that will not stay fixed.</h1><p className="work-lede">I’m Sean McDonnell. I work across support, implementation, backend systems, integrations, and applied AI. I trace failures to their source, build the repair, and leave the next person with evidence they can use.</p><div className="work-actions"><a className="primary-action" href="mailto:nextelevenstudios@gmail.com?subject=Engineering%20role">Contact for roles <span>↗</span></a><a href="/downloads/Sean-McDonnell-Technical-Support-Implementation-Engineer-Resume.pdf">Download résumé <span>↓</span></a></div></section>
  <section className="work-section"><div><p className="section-label">Target roles</p><h2>Work that crosses the interface and the system behind it.</h2></div><ul className="role-list">{roles.map((role,index)=><li key={role}><span>{String(index+1).padStart(2,"0")}</span>{role}</li>)}</ul></section>
  <section className="work-section"><div><p className="section-label">Selected proof</p><h2>Specific evidence. Explicit limits.</h2></div><div className="proof-grid">{proof.map(item=><article key={item.value+item.label}><strong>{item.value}</strong><p>{item.label}</p><small>{item.boundary}</small></article>)}</div></section>
  <section className="work-section"><div><p className="section-label">Stack</p><h2>Current working range.</h2></div><div className="stack-lines"><p><span>Languages</span>Python · Rust · TypeScript / JavaScript · Kotlin · Swift · SQL · Bash</p><p><span>Backend + data</span>FastAPI · REST APIs · PostgreSQL / pgvector · SQLite · Redis · Docker</p><p><span>AI + retrieval</span>LLM APIs · tool calling · MCP · embeddings · RAG · hybrid retrieval · reranking · citations · evaluation</p><p><span>Interfaces + delivery</span>React · Next.js · SwiftUI · Jetpack Compose · GitHub Actions · automated testing · CI</p></div></section>
  <section className="work-section"><div><p className="section-label">How I work</p><h2>Investigate. Implement. Hand off.</h2></div><ol className="method-grid"><li><span>01</span><h3>Investigation</h3><p>Reproduce the failure. Read the logs. Separate the visible symptom from the system that caused it.</p></li><li><span>02</span><h3>Implementation</h3><p>Define the boundary. Build the narrowest complete repair. Test normal operation and the failure paths that matter.</p></li><li><span>03</span><h3>Handoff</h3><p>Document the limits, checks, and operating path so the work can survive without the person who wrote it.</p></li></ol></section>
  <section className="contact-strip"><p className="section-label">Role conversation</p><h2>Contact me directly.</h2><div><a className="primary-action" href="mailto:nextelevenstudios@gmail.com?subject=Engineering%20role">Contact for roles <span>↗</span></a><a href="https://www.linkedin.com/in/mothership-ai">LinkedIn <span>↗</span></a></div></section>
  <section className="consulting-section"><div className="path-label secondary"><span>02</span> Scoped consulting · Secondary path</div><div className="consulting-grid"><div><h2>One broken workflow. One accountable engineer.</h2></div><div><p>NextEleven takes owner-operated engagements with a real boundary: a difficult failure, an incomplete implementation, a backend or integration, a retrieval workflow, or a system that needs stabilization and a usable handoff.</p><p>Start with the work that is failing now. Define done in writing. Expand only if the first piece proves useful.</p><Link className="secondary-action" href="mailto:nextelevenstudios@gmail.com?subject=Scoped%20build">Discuss a scoped build <span>↗</span></Link></div></div></section>
</main><SiteFooter/></>; }
