"use client";
import Link from "next/link";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
const InstrumentHero = dynamic(() => import("./InstrumentHero").then((m) => m.InstrumentHero), { ssr: false });
const panels = [
 {id:"about",index:"01",eyebrow:"About",title:"Who leads the work.",sentence:"Sean McDonnell is a DFW-based engineer, consultant, and owner of NextEleven.",destination:"/about",action:"Meet Sean"},
 {id:"work",index:"02",eyebrow:"Work",title:"Hire or contract.",sentence:"Bring Sean or NextEleven in for IT, software, AI, support, implementation, or technical delivery.",destination:"/work",action:"See ways to work"},
 {id:"build",index:"03",eyebrow:"Build",title:"Build what matters.",sentence:"From a public website to enterprise-grade software and applied AI inside the operation.",destination:"/build",action:"See what we build"},
 {id:"presence",index:"04",eyebrow:"Presence",title:"Start with the front door.",sentence:"Websites, portals, bilingual journeys, and inquiry paths—the most common way to start with NextEleven.",destination:"/presence",action:"Explore web presence"}
] as const;
function useHeroEnhancement(){const [enabled,setEnabled]=useState(false);useEffect(()=>{const motion=matchMedia("(prefers-reduced-motion: reduce)");const desktop=matchMedia("(min-width: 900px)");const connection=(navigator as Navigator & {connection?:{saveData?:boolean}}).connection;const update=()=>{let webgl=false;try{const canvas=document.createElement("canvas");webgl=Boolean(canvas.getContext("webgl2")||canvas.getContext("webgl"))}catch{}setEnabled(!motion.matches&&desktop.matches&&!connection?.saveData&&webgl)};update();motion.addEventListener("change",update);desktop.addEventListener("change",update);return()=>{motion.removeEventListener("change",update);desktop.removeEventListener("change",update)}},[]);return enabled}
export function HomePanels(){const heroEnabled=useHeroEnhancement();const [active,setActive]=useState(0);const [heroVisible,setHeroVisible]=useState(true);useEffect(()=>{const els=panels.map(p=>document.getElementById(p.id)).filter(Boolean) as HTMLElement[];const heroObserver=new IntersectionObserver(([entry])=>setHeroVisible(entry.isIntersecting),{threshold:.01});if(els[0])heroObserver.observe(els[0]);let frame=0;const update=()=>{frame=0;const center=window.innerHeight/2;let nearest=0;let distance=Infinity;els.forEach((el,index)=>{const rect=el.getBoundingClientRect();const next=Math.abs(rect.top+rect.height/2-center);if(next<distance){distance=next;nearest=index}});setActive(nearest)};const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update)};update();window.addEventListener("scroll",onScroll,{passive:true});window.addEventListener("resize",onScroll);return()=>{heroObserver.disconnect();window.removeEventListener("scroll",onScroll);window.removeEventListener("resize",onScroll);if(frame)cancelAnimationFrame(frame)}},[]);return <>
 <a className="skip-link" href="#about">Skip to the first panel</a>
 <header className="site-header"><Link href="/" className="wordmark" aria-label="NextEleven home">NEXT<span>ELEVEN</span></Link><p>Mansfield · DFW</p></header>
 <nav className="progress" aria-label="Home sections">{panels.map((p,i)=><a key={p.id} className={active===i?"active":""} href={`#${p.id}`} onClick={()=>setActive(i)} aria-current={active===i?"location":undefined}><span>{p.index}</span> {p.eyebrow}</a>)}</nav>
 <main className="panel-stack">{panels.map((p,i)=><section className={`panel panel-${p.id}`} id={p.id} key={p.id} aria-labelledby={`${p.id}-title`}>
  {i===0&&<div className="hero-field" aria-hidden="true"><div className="hero-poster"/>{heroEnabled&&<InstrumentHero active={heroVisible}/>}</div>}
  <Link href={p.destination} className="panel-link" aria-label={`${p.action}: ${p.title}`}><span className="panel-index" aria-hidden="true">{p.index}</span><div className="panel-copy"><p className="eyebrow">{p.eyebrow}</p><h1 id={`${p.id}-title`}>{p.title}</h1><p className="sentence">{p.sentence}</p><span className="destination">{p.action}<i aria-hidden="true">↗</i></span></div><span className="panel-rule" aria-hidden="true"/></Link>
 </section>)}</main></>}
