import type { Metadata } from "next";
import { InnerHeader } from "@/components/shell/InnerHeader";
import { SiteFooter } from "@/components/shell/SiteFooter";
export const metadata:Metadata={title:"Web presence",description:"NextEleven builds custom marketing sites, bilingual properties, inquiry paths, and portal foundations for established businesses."};
const includes=["Customer and business mapping","Site architecture and messaging","Custom responsive design system","Fast, accessible implementation","Inquiry paths and contact routing","Technical search foundations","Analytics and launch preparation","Vercel delivery and source handoff"] as const;
const process=[
 {index:"01",title:"Map",copy:"Learn the business, its customers, the current presence, and the actions the site needs to make clear."},
 {index:"02",title:"Scope",copy:"Define the pages, content ownership, inquiry routes, acceptance conditions, exclusions, and production responsibilities."},
 {index:"03",title:"Build",copy:"Design and implement the responsive system. Connect the agreed paths. Test content, forms, accessibility, and performance."},
 {index:"04",title:"Launch",copy:"Complete staging review, production checks, DNS work, account ownership, documentation, and handoff."}
] as const;
const service={"@context":"https://schema.org","@type":"ProfessionalService","@id":"https://mothership-ai.com/presence#service",name:"NextEleven Web Presence",url:"https://mothership-ai.com/presence",email:"nextelevenstudios@gmail.com",telephone:"833-925-6048",areaServed:"United States",parentOrganization:{"@id":"https://mothership-ai.com/#organization"},address:{"@type":"PostalAddress",addressLocality:"Mansfield",addressRegion:"TX",addressCountry:"US"}};
export default function PresencePage(){return <><InnerHeader current="presence"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(service).replace(/</g,"\\u003c")}}/><main className="presence-main"><section className="presence-hero"><p className="section-label">04 · Web presence</p><h1>Make the business easier to understand, trust, and reach.</h1><p>NextEleven builds custom marketing sites, bilingual properties, buyer and seller journeys, inquiry paths, and portal foundations that can grow with the operation.</p><a className="primary-action" href="mailto:nextelevenstudios@gmail.com?subject=Web%20presence%20project%20brief">Send a project brief <span>↗</span></a></section><section className="presence-includes"><div><p className="section-label">The engagement</p><h2>A complete public foundation.</h2><p>One accountable builder from definition through launch. The result is a working property the client can own, move, and extend.</p></div><ul>{includes.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ul></section><section className="presence-example"><div><p className="section-label">Public example</p><h2>JP Transmission.</h2></div><div><p>NextEleven designed and implemented a bilingual web presence with distinct buyer and seller journeys, responsive presentation, and a configured inquiry path.</p><p>The production foundation keeps deeper operating claims behind the correct gate: live inventory, ecommerce, checkout, customer accounts, fulfillment, and audited stock movement are not implied by the public site.</p><a href="https://jp-transmission-recycle.vercel.app">View the public example ↗</a></div></section><section className="presence-process"><p className="section-label">Process</p><h2>Map → scope → build → launch.</h2><ol>{process.map(step=><li key={step.index}><span>{step.index}</span><h3>{step.title}</h3><p>{step.copy}</p></li>)}</ol></section><section className="phase-two"><p className="section-label">Phase two</p><div><h2>Operations begin only when the business truth is ready.</h2><p>Checkout, live inventory, customer accounts, payments, shipping, tax, fitment, fulfillment, and operational integrations require authoritative data, defined workflows, acceptance testing, and a separate written scope.</p></div></section><a className="presence-cta" href="mailto:nextelevenstudios@gmail.com?subject=Web%20presence%20project%20brief"><strong>What needs to work?</strong><span>Send a project brief ↗</span></a></main><SiteFooter/></>}
